Repository CS2103JAN2018-F14-B2/main, pull requests merged in 2018-03, with the labels that each got.

#9 Enhancement to Storage component
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
Labels: type.enhancement

#6 Enhancement to Logic component
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.enhancement

#3 Update URL in Doc and update User stories
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.story

#14 Enhancement to UI component
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.enhancement

#15 Update documents
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/aquarinte.png
Labels: type.task

#25 Personal info
  docs/AboutUs.adoc
  docs/images/wynonaK.png
Labels: type.task

#29 Updated AboutUs
  docs/AboutUs.adoc
  docs/images/lejing.jpg
Labels: type.task

#31 Updated README
  README.adoc
Labels: type.task

#30 Update About us
  docs/AboutUs.adoc
  docs/images/Robert_Peng.jpg
Labels: type.task

#32 Update UI diagram
  docs/images/Ui.png
Labels: type.task

#33 Update and add new user stories
  README.adoc
  docs/DeveloperGuide.adoc
Labels: type.story, type.task

#34 Update acknowledgement
  README.adoc
Labels: type.task

#26 Add support for changing theme
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/ChangeThemeRequestEvent.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/model/theme/Theme.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
  src/test/java/seedu/address/model/theme/ThemeTest.java
  src/test/java/seedu/address/testutil/TypicalThemes.java
Labels: type.enhancement

#27 Add Pet Patient Implemented
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddPetPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddPetPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/petpatient/PetPatient.java
  src/main/java/seedu/address/model/petpatient/PetPatientName.java
  src/main/java/seedu/address/model/petpatient/UniquePetPatientList.java
  src/main/java/seedu/address/model/petpatient/exceptions/DuplicatePetPatientException.java
  src/main/java/seedu/address/model/petpatient/exceptions/PetPatientNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/petpatient/PetPatientNameTest.java
Labels: priority.high, type.story

#28 Enhancement: Add Appointment
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Remark.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/appointment/RemarkTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
Labels: priority.high, type.story

#22 Add NRIC in Person and edit command to change NRIC
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.medium, type.enhancement, type.story

#37 Features contribution
  docs/DeveloperGuide.adoc
Labels: type.task

#38 Indicate features
  docs/DeveloperGuide.adoc
Labels: type.task

#40 Update DG
  docs/DeveloperGuide.adoc
Labels: type.task

#41 Updated AboutUs
  docs/AboutUs.adoc
Labels: type.task

#43 Use CalendarFX to display Calendar View
  build.gradle
  lib/README-EXT.txt
  lib/calendarfx-recurrence-8.4.0.jar
  lib/calendarfx-view-8.4.0.jar
  lib/controlsfx-8.40.11.jar
  lib/fontawesomefx-commons-8.13.jar
  lib/fontawesomefx-fontawesome-4.7.0-1.jar
  lib/license4j-1.4.0.jar
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.high, type.enhancement

#54 Combine 3 different add commands into a single main command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddPetPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPetPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/petpatient/PetPatient.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, type.enhancement

#49 Implemented storing of PetPatient details
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/petpatient/UniquePetPatientList.java
  src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high, type.story

#56 Fixed PetPatient class
  src/main/java/seedu/address/model/petpatient/PetPatient.java
Labels: severity.High, type.bug

#57 Add DG implementation
  docs/DeveloperGuide.adoc
Labels: type.task

#59 Update light theme
  src/main/resources/view/LightTheme.css
Labels: type.task

#58 Update DG to add implementation for Add and Storing of Appointments
  docs/DeveloperGuide.adoc
Labels: type.task

#62 Update DG about calendar view
  docs/DeveloperGuide.adoc
Labels: type.task

#71 Update DG on certain prefaces
  docs/DeveloperGuide.adoc
Labels: type.task

#76 Update documents
  README.adoc
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: type.task

#77 Update UG
  docs/UserGuide.adoc
Labels: type.task

#75 Storage Enhancements for PetPatients
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
  src/test/java/seedu/address/storage/XmlAdaptedPetPatientTest.java
  src/test/java/seedu/address/testutil/PetPatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
Labels: priority.high, type.enhancement

#72 Updated XmlAdaptedAppointment, Added UniqueAppointmentTag Field
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: priority.high, type.task

#82 Fixed Storage and Tagging Issues
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
Labels: priority.high, type.story

#85 Fix add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateNricException.java
  src/main/java/seedu/address/model/petpatient/PetPatientName.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, type.enhancement

#86 Minor Edits
  README.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/model/petpatient/PetPatient.java
  src/main/java/seedu/address/model/petpatient/PetPatientName.java
  src/main/java/seedu/address/model/petpatient/UniquePetPatientList.java
  src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/pawprint.png
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/model/petpatient/PetPatientNameTest.java
  src/test/java/seedu/address/testutil/PetPatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
Labels: priority.medium, type.task

#99 Add support for basic autocomplete
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/autocomplete.png
  src/main/java/seedu/address/logic/CommandSyntaxWords.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: merge.ready, type.enhancement

#109 Implemented EditCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: merge.ready, priority.high, type.task

#100 Revised priorities of user stories
  docs/DeveloperGuide.adoc
Labels: merge.ready, type.task

#105 Created PetPatientCard and Panel & Update GUI test
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PetPatientPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PetPatientCard.java
  src/main/java/seedu/address/ui/PetPatientListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PetPatientListCard.fxml
  src/main/resources/view/PetPatientListPanel.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/PetPatientCardHandle.java
  src/test/java/guitests/guihandles/PetPatientListPanelHandle.java
  src/test/java/seedu/address/ui/PetPatientCardTest.java
  src/test/java/seedu/address/ui/PetPatientListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: merge.ready, priority.high

#113 Appointments are unique based on datetime.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateDateTimeException.java
Labels: merge.ready, type.bug
