Repository CS2103JAN2018-F14-B2/main, pull requests merged in 2018-04, with the labels that each got.

#117 Update delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
Labels: merge.ready, type.bug

#123 Update and add new JUnit tests for AddCommand
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: merge.ready, type.task

#126 Update code and add JUnit tests for Add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: merge.ready, type.enhancement

#128 Adding data to SampleDataUtil
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Remark.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentDependencyNotEmptyException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateDateTimeException.java
  src/main/java/seedu/address/model/petpatient/exceptions/PetDependencyNotEmptyException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/address/model/appointment/RemarkTest.java
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
  src/test/java/seedu/address/storage/XmlAdaptedAppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/SampleDataTest.java
Labels: merge.ready, priority.medium, type.task

#139 Basic Find Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameNricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/petpatient/PetPatientOwnerNricContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: merge.ready, priority.high, type.story, type.task

#137 Update UG
  docs/UserGuide.adoc
  docs/images/add_examples.PNG
  docs/images/autocomplete.png
Labels: type.task

#141 Update examples image for add command
  docs/UserGuide.adoc
  docs/images/add_examples.PNG
Labels: type.task

#146 Implemented Edit Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: merge.ready, priority.high, type.story, type.task

#151 Update UserGuide and images for command Results
  docs/UserGuide.adoc
  docs/images/After_Clear.PNG
  docs/images/After_Delete.PNG
  docs/images/After_Undo.PNG
  docs/images/History_Command.PNG
  docs/images/List_Command.PNG
  docs/images/Redo_Clear.PNG
  docs/images/Redo_Fail.PNG
  docs/images/Redo_Success.PNG
  docs/images/Theme_Dark.PNG
  docs/images/Theme_Light.PNG
  docs/images/Undo_Clear.PNG
  docs/images/Undo_Fail.PNG
Labels: type.task

#156 Update UG and add new light theme
  docs/UserGuide.adoc
  docs/images/Theme_Light.PNG
  src/main/resources/view/LightTheme.css
Labels: merge.ready, type.task

#152 Updated UG
  docs/UserGuide.adoc
  docs/images/edit_examples.PNG
Labels: merge.ready, priority.high, type.task

#158 Update autocomplete case-insensitive
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.enhancement

#163 Update collate and update addCommandSystemTest
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/testutil/PetPatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: type.task

#160 Updating UG
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.task

#164 Add collate files for v1.4
  collated/functional/Robert-Peng.md
  collated/functional/aquarinte.md
  collated/functional/chialejing.md
  collated/functional/wynonaK-reused.md
  collated/functional/wynonaK.md
  collated/test/Robert-Peng.md
  collated/test/aquarinte.md
  collated/test/chialejing.md
  collated/test/wynonaK.md
  src/main/resources/view/LightTheme.css
Labels: priority.high, type.task

#166 Fixes to some bugs, Added test cases for Delete and Find
  build.gradle
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentDependencyNotEmptyException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/petpatient/exceptions/PetDependencyNotEmptyException.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: merge.ready, priority.medium, type.bug, type.task

#174 Update UserPrefs and store theme selection in preferences.json
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/ChangeThemeCommand.java
  src/main/java/seedu/address/logic/parser/ChangeThemeCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/theme/Theme.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/theme/ThemeTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalThemes.java
Labels: merge.ready, type.enhancement, type.task

#187 Fix the UI bugs
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: merge.ready, type.bug

#179 CalendarView command to switch between Pageviews
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarViewEvent.java
  src/main/java/seedu/address/logic/commands/CalendarViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CalendarViewCommandParser.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/test/java/systemtests/CalendarViewCommandSystemTest.java
Labels: merge.ready, priority.medium, type.enhancement

#188 Update UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/logic/commands/ChangeThemeCommandTest.java
Labels: merge.ready, type.task

#189 Pet Patient Field Checking
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/petpatient/BloodType.java
  src/main/java/seedu/address/model/petpatient/Breed.java
  src/main/java/seedu/address/model/petpatient/Colour.java
  src/main/java/seedu/address/model/petpatient/PetPatient.java
  src/main/java/seedu/address/model/petpatient/Species.java
  src/main/java/seedu/address/model/petpatient/exceptions/DuplicatePetPatientException.java
  src/main/java/seedu/address/model/petpatient/exceptions/PetPatientNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPetPatient.java
  src/main/java/seedu/address/ui/PetPatientCard.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPetPatientTest.java
  src/test/java/seedu/address/testutil/PetPatientBuilder.java
  src/test/java/seedu/address/testutil/PetPatientUtil.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, severity.Low, type.bug

#191 View appointment
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: merge.ready, priority.high

#190 Refactored Edit Command + JUnit Tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/descriptors/EditAppointmentDescriptor.java
  src/main/java/seedu/address/logic/descriptors/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/descriptors/EditPetPatientDescriptor.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/petpatient/Colour.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditPetPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/UniquePetPatientListTest.java
  src/test/java/seedu/address/model/petpatient/BloodTypeTest.java
  src/test/java/seedu/address/model/petpatient/BreedTest.java
  src/test/java/seedu/address/model/petpatient/ColourTest.java
  src/test/java/seedu/address/model/petpatient/PetPatientNameTest.java
  src/test/java/seedu/address/model/petpatient/SpeciesTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPetPatientDescriptorBuilder.java
Labels: merge.ready, priority.high, type.task

#192 Find ParserUtil and Relevant Tests
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: merge.ready, priority.medium, type.task

#193 Improved autocomplete
  src/main/java/seedu/address/logic/CommandSyntaxWords.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: merge.ready, type.enhancement

#199 Improve autocomplete for tags
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: merge.ready, type.enhancement

#200 List Appointment
  src/main/java/seedu/address/commons/events/ui/ChangeCalendarViewEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeDayViewRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeMonthViewRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeWeekViewRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ChangeYearViewRequestEvent.java
  src/main/java/seedu/address/logic/commands/CalendarViewCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CalendarViewCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/exceptions/NoAppointmentInYearException.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/ListAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/CalendarViewCommandSystemTest.java
  src/test/java/systemtests/ListAppointmentCommandSystemTest.java
Labels: merge.ready, priority.high, type.epic, type.story, type.task

#203 Implement size restriction for autocomplete suggestion list and some minor fixes/improvements
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: merge.ready, type.enhancement

#205 Implement descriptions for options and prefixes in autocomplete drop down menu
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: merge.ready, type.enhancement

#206 Interval fixed to 30
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: merge.ready, severity.High, type.bug

#207 Update docs
  .circleci/config.yml
  README.adoc
  docs/team/Chia Le Jing.adoc
  docs/team/Jacqueline Cheong.adoc
  docs/team/Peng Xuan Chang.adoc
  docs/team/Wynona Kaan.adoc
Labels: type.task

#213 Update Add command error messages and JUnit tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ChangeThemeCommandParserTest.java
  src/test/java/seedu/address/model/theme/ThemeTest.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalPetPatients.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: merge.ready, type.task

#212 Fix List view color bug
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: merge.ready, severity.Medium, type.bug

#214 Modify UG structure and made some amendments
  docs/UserGuide.adoc
Labels: UGDG, merge.ready, type.task

#196 Show tabs for each panelList
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PetPatientListPanel.fxml
Labels: merge.ready, type.enhancement

#215 Add key to toggle autocomplete on/off
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: merge.ready, type.enhancement

#216 Update UI
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PetPatientListPanel.fxml
Labels: merge.ready, type.task

#219 Refactoring Find Command, Adding New Tests
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: merge.ready, priority.medium, type.task

#218 Edit Command Tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: merge.ready, priority.high, type.task

#221 Update Documents
  docs/team/Chia Le Jing.adoc
Labels: type.task

#220 Update docs
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Theme_Dark.PNG
  docs/images/Ui.png
  docs/images/autocomplete.png
  docs/team/Jacqueline Cheong.adoc
Labels: merge.ready, type.task

#224 Update collate files
  collated/functional/Robert-Peng.md
  collated/functional/aquarinte-reused.md
  collated/functional/aquarinte.md
  collated/functional/chialejing-reused.md
  collated/functional/chialejing.md
  collated/functional/wynonaK.md
  collated/test/Robert-Peng.md
  collated/test/aquarinte.md
  collated/test/chialejing.md
  collated/test/wynonaK.md
  src/main/resources/view/LightTheme.css
Labels: type.task

#225 Minor Edits
  docs/UserGuide.adoc
  docs/team/Chia Le Jing.adoc
  src/main/java/seedu/address/MainApp.java
Labels: type.task

#228 Implemented Checks for Edit Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: merge.ready, priority.high, severity.High

#227 Exception update
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
Labels: merge.ready, priority.medium

#229 Added minor tests and more Sample Data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/ListAppointmentCommandSystemTest.java
Labels: merge.ready, priority.medium, type.enhancement

#230 More Exception update
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
Labels: merge.ready

#231 Update ui
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PetPatientCard.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.task

#232 Updates for Add Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: merge.ready, type.task

#233 Update autocomplete
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: merge.ready, type.task

#234 Update ui and messages for existing commands
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: merge.ready, type.task

#236 Update owner/person to contact, update addressbook to medeina.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/exceptions/ConcurrentAppointmentException.java
  src/main/java/seedu/address/model/appointment/exceptions/PastAppointmentException.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateNricException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: merge.ready, priority.medium, type.task

#238 Updated Error Messages
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: merge.ready, priority.high, type.task

#239 Minor code update
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/Autocomplete.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: merge.ready

#237 Updated UG
  docs/UserGuide.adoc
Labels: UGDG, merge.ready, priority.high

#235 Update DG UG Portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Show_Appointment.PNG
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagram1.png
  docs/team/Peng Xuan Chang.adoc
Labels: UGDG, merge.ready

#241 Bug Fixed
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.high, severity.High, type.bug

#242 Update UG DG
  docs/UserGuide.adoc
  docs/images/After_Clear.PNG
  docs/images/After_Delete.PNG
  docs/images/After_Undo.PNG
  docs/images/History_Command.PNG
  docs/images/List_Command.PNG
  docs/images/Redo_Clear.PNG
  docs/images/Redo_Fail.PNG
  docs/images/Redo_Success.PNG
  docs/images/Screen_Shot.png
  docs/images/Show_Appointment.png
  docs/images/Ui.png
  docs/images/Undo_Clear.PNG
  docs/images/Undo_Fail.PNG
  docs/team/Peng Xuan Chang.adoc
Labels: UGDG, merge.ready

#244 Update docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentCommandClassDiagram.pptx
  docs/diagrams/command syntax.pptx
  docs/images/LogicCommandClassDiagram.png
  docs/images/Theme_Dark.PNG
  docs/images/Theme_Light.PNG
  docs/images/add_examples.PNG
  docs/images/autocomplete.png
  docs/images/autocompleteSequenceDiagram.png
  docs/images/colours.png
  docs/images/commandSyntax.png
Labels: UGDG, merge.ready

#243 Developers Guide Updates
  docs/DeveloperGuide.adoc
  docs/diagrams/DeleteCommandOwnerSequenceDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagramListAppt.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/UpdatedModelComponentClassDiagram.pptx
  docs/images/DeleteDependenciesForForce.png
  docs/images/DeletePersonDiagramForDelete.png
  docs/images/ListAppointmentDayView.PNG
  docs/images/ModelClassDiagramUpdated.PNG
  docs/images/SDforDeletePerson.png
  docs/images/SDforListAppointment.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: UGDG, merge.ready, priority.high, userTest.bug

#249 Fix + Added JUnit Test for EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.high, severity.High, type.bug

#248 Update Docs
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addCommandSequenceDiagram.png
  docs/images/autocomplete.png
  docs/team/Jacqueline Cheong.adoc
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: UGDG
